/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 01.07.2026 19:35:52

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 10128;
#else
constexpr int kTensorArenaSize = 9104;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,3960 } };
const TfArray<1, float> quant0_scale = { 1, { 0.00390625, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 99, 40, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 99, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 50, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 50, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 400, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data6[7] = { -65, 868, -2377, 246, 2560, -1645, 11, };
const TfArray<1, int> tensor_dimension6 = { 1, { 7 } };
const TfArray<1, float> quant6_scale = { 1, { 8.4581261035054922e-05, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[7*400] = { 
  41, 19, 26, 11, -3, -32, -8, 17, 28, 12, -21, -12, -30, -8, 0, -26, 9, -2, 33, -29, -14, -15, -60, -11, 13, -15, -41, -33, 16, -30, -1, -17, 15, 7, 6, 22, 60, 50, -1, 12, 5, 37, 29, -71, 1, -66, 10, 3, 16, 33, 32, 28, 19, 14, 22, -1, 21, 28, 3, -33, 7, -41, -2, 4, 15, -1, 15, -43, -100, -66, -61, 3, 2, -72, -127, -3, 3, -47, 19, -15, -13, -2, 8, -3, 4, -10, 0, -12, -2, -21, -4, -20, 12, -2, 2, -1, -14, -4, 2, 14, -14, 12, -28, -3, -8, 6, -24, 0, 0, -45, -15, 5, 20, 25, 36, -1, -15, -7, -58, -4, -4, 22, -18, -5, 11, -64, -1, -13, 12, 16, 17, 18, 5, 31, 13, -7, -3, 39, 17, -17, 2, -68, 5, -1, 9, 6, 14, -16, -17, -1, 4, 11, 35, 17, -21, -11, 3, -41, 19, -16, 19, 9, 11, 8, -12, -4, -36, -21, 11, 23, 0, -8, -13, -18, -8, -16, -3, 8, 15, 28, 5, 34, 20, 0, 29, 33, 33, -8, -4, -28, -9, -15, 21, 25, 23, -3, -51, -39, -65, 14, 32, -12, -69, -9, 18, -32, 19, -11, -2, -15, 11, -15, -14, -35, -29, -4, 7, 2, 15, -29, 37, -43, 2, -6, 2, 16, 0, 30, 36, 38, 43, -3, 14, 27, 47, -9, -23, -24, -13, 16, 14, 26, 31, 13, -17, -24, -19, 11, 20, 0, -21, -14, 12, -42, -10, -24, 6, 8, 18, -33, -36, -17, -41, -3, 11, -8, -30, 8, 32, -28, 1, -26, 4, -20, -7, 23, 24, 58, 5, -3, 12, 34, 24, -8, -30, -24, -22, 2, 26, 19, 9, 10, -20, 9, -4, 14, 31, 30, 7, -13, 6, -17, -8, -16, 25, 25, 30, -43, -83, -75, -92, -9, 10, -47, -86, -14, 23, -25, 15, -20, -34, 13, 1, 4, 9, 8, 11, -6, 10, 15, 14, -17, 25, -18, -16, -6, 8, -2, 12, 32, -4, 20, 30, 6, 16, 26, 28, -2, -4, -38, -8, -1, 32, 27, 41, -34, -84, -48, -67, -6, 18, -21, -73, -6, 18, -66, 11, -25, 23, -4, 29, -7, -27, -26, -47, -22, 20, -7, -16, 5, 29, -12, -11, -20, -1, 14, 11, 37, 47, 58, 37, 0, 9, 38, 11, 12, 10, -40, -50, -5, 
  6, 4, 7, -3, 6, -17, -19, -1, 3, 0, -23, -11, -12, -4, 5, 41, -24, -1, -9, 32, -7, -3, 5, 5, -3, 21, -19, -32, 8, 5, -6, 43, -9, -17, -10, 29, -7, -13, -6, 14, -5, 7, -16, -19, -3, -5, -3, 45, -42, 11, 7, 21, -11, -4, -36, 7, -8, 8, -41, -28, -4, -10, -16, 43, -10, -11, -9, 22, 15, 8, 8, 16, -27, 11, -14, -35, -27, 16, 2, 46, 14, 8, 15, 13, 17, 12, 12, 13, 17, 3, -33, -18, -8, -20, 1, 25, -6, 9, 1, 11, 2, -10, 8, -2, -6, 13, -16, -19, 15, -8, -9, 11, -16, 0, -15, 13, -8, 8, 8, 2, 11, -4, -20, -30, -10, -8, -24, 39, -17, -3, 6, 9, -6, -24, -19, 0, 0, -2, -50, -19, 4, 12, -25, 34, -15, -9, -3, 20, -17, -3, 5, 2, -14, 15, -10, -23, -7, 4, -20, 55, 5, 24, -2, 26, -5, 5, -10, -12, 2, -4, -21, -21, 1, -2, 4, 26, -29, 9, 15, 24, -6, -9, -13, -3, -19, -11, -50, -11, 7, 24, -20, 46, -21, 12, -3, 17, -2, -13, -11, -2, -6, 9, -26, -1, -27, 24, -11, 49, -13, -18, -10, 10, 5, -9, -23, 18, -8, -4, -34, -29, -9, 4, -12, 49, -16, 6, 13, 4, 0, -5, -25, -24, -17, -11, -61, -17, -5, 15, -26, 29, -23, 1, -10, 10, 6, 4, -8, 8, -1, 5, -26, -20, -8, 14, -7, 49, -24, 12, -1, -1, 31, -1, -9, 3, -13, 10, -22, -21, -48, 8, -14, 41, -15, 9, 1, -14, 2, -26, -29, -4, -12, 8, -12, -7, -21, 18, -23, 37, -38, 5, -10, 15, -1, -4, -34, -16, -6, -19, -28, -11, -30, 1, -17, 33, -15, 11, -9, 14, 6, 6, -7, -6, -2, 15, 2, -23, -7, 1, -23, 53, -15, -4, 13, -3, -2, 5, -33, -16, -19, -12, -36, -19, -40, 19, -22, 34, -9, -10, 13, 13, -9, -3, -38, 4, -12, -8, -50, -5, -29, 5, -23, 36, -11, 17, -3, -7, 6, -29, -9, -7, -14, 2, -7, -14, -15, 1, -20, 42, -10, 29, 9, 0, -19, -7, -34, 0, -4, 0, -71, -39, -12, 12, 2, 42, -30, 1, 28, -18, 2, -37, -13, -2, -3, -24, -81, -33, -14, 1, -11, 36, 
  8, 13, 13, -30, 18, 27, -25, -11, 6, -36, -60, -12, 9, 10, 19, -5, 9, 31, 0, -37, 3, -2, -18, 0, -2, -81, -45, -14, -5, 37, 18, -17, 25, -7, -6, -20, -9, 24, -28, -4, 13, -79, -39, 19, -6, -1, 12, -20, 5, -4, -3, -34, 5, 27, -55, -4, 1, -57, -36, -19, 26, 9, 10, -1, 13, -24, -18, -52, 3, 22, -14, 8, -6, -57, -79, 18, 15, 7, 12, -2, -16, -10, 11, -7, 7, 4, -26, -12, 6, 6, 7, -18, 1, -23, -1, -3, 10, 4, 10, -38, 6, 37, -32, 2, 9, -37, -34, 3, -8, 14, -5, -18, 11, 19, 5, -12, 1, 31, -16, 5, 2, -64, -30, 24, 14, -3, 4, -38, 9, 25, 1, -45, -15, 51, -9, -1, 21, -69, -48, 23, 6, 25, 19, -21, 15, 20, 1, -24, -7, 24, -11, 10, 15, -31, -41, -28, 7, 21, 20, -27, 1, 6, -12, -6, 10, 35, -32, -13, -8, -50, -29, -6, -8, 23, -10, -9, 19, 22, 15, -15, 5, 17, -1, -3, 10, -57, -26, -34, 9, 14, 21, -31, 11, 18, -1, -47, -1, 17, 5, 1, 29, -63, -53, -34, -10, 38, 14, -16, 14, 3, 13, -7, -1, 3, -10, 10, 5, -58, -74, 7, 12, 22, 13, -19, -7, 12, 17, -8, -1, 34, -28, 18, 9, -75, -64, 1, 2, 28, 8, -24, 7, 5, 20, -26, -5, 28, -23, 1, 10, -53, -25, -16, 30, 20, 22, -23, -5, 29, 12, -41, 13, 27, -4, 8, -12, -44, -61, 17, -8, 20, 25, -32, 12, 16, -7, -36, -4, 24, 10, 0, 6, -59, -35, -26, 5, 20, 3, -24, 7, 19, 2, -21, 10, 34, -11, -6, 2, -60, -39, -14, 4, 13, 24, -13, 5, 7, 16, -69, -11, 40, -12, 17, -2, -78, -66, -6, 11, 16, 9, -1, 0, 30, 4, -41, 8, 39, 1, 12, 17, -67, -48, 9, -13, 14, 23, -9, 11, 15, 13, -38, 7, 23, -30, 26, 0, -54, -38, -11, -14, 27, 20, -21, 12, 22, -1, -32, 1, 26, -16, 3, 28, -61, -23, -11, -8, 12, -1, -9, 11, 13, 21, -15, -28, 29, -34, 12, 6, -52, -44, 30, 14, 11, 13, -19, 10, 20, 7, -33, -19, 28, -31, 2, -7, -70, -27, 8, 13, 4, 2, -1, 
  -44, -26, -56, -33, 21, 18, -3, 22, -7, 35, 14, -2, -21, -16, -41, -46, -58, -8, -16, -32, 25, -6, -3, 3, -32, 11, -20, 15, -4, -4, -48, -51, -22, 1, -36, -25, 17, 9, -13, 12, -34, 1, -2, -1, -2, -25, -56, -52, -13, 7, -4, -25, 17, -18, -12, 5, -12, 9, 2, -6, 16, 1, -54, -40, -26, -17, -19, -32, 38, 7, -18, 2, 9, 23, -39, -5, 4, 4, -21, -32, -5, 20, 6, 9, 7, 24, 8, 36, -4, -15, 31, -8, -4, 26, 12, -11, -18, 4, -18, -7, 33, 26, 7, 24, -21, 10, -17, 19, 2, -22, -6, -26, -54, -20, -22, -15, 26, 13, -10, -12, -31, 26, -13, -22, 2, -1, -42, -62, -39, 2, -24, -11, 31, -6, -18, 15, -25, 19, -10, 11, 5, 13, -61, -38, -17, -20, -26, -17, 39, 22, -30, 10, -16, 9, -21, 11, -12, 0, -16, -20, -53, -2, -2, -33, 34, 9, -7, 10, -13, 9, -45, 17, 17, 17, -36, -20, -56, 7, -29, -23, 20, -4, -8, -9, -6, 26, -1, 6, 11, -37, -41, -58, -31, 10, -19, -21, 18, 5, -12, 19, -25, 17, 7, 24, 10, -1, -48, -58, -36, -15, 2, -21, 11, -15, 7, 3, -18, 16, -5, -10, -9, 6, -33, -40, -32, 1, -23, -31, 6, 13, -19, 4, 4, 2, -1, -5, -5, -13, -53, -34, -19, -13, -21, -19, 8, 6, -9, -4, -14, 32, 21, -13, -17, -3, -49, -65, -37, 5, -22, -10, 21, 2, -2, 8, -7, 10, 9, -2, -7, 14, -34, -43, -47, 15, -10, -19, 24, -18, 13, 0, -9, 27, -22, 12, 4, 11, -15, -58, -11, -19, -27, -28, 21, -6, -11, 11, -32, 10, -17, -2, -21, -22, -50, -9, -50, 5, -32, -45, 29, -9, -8, 15, -29, 21, -10, 4, -10, -2, -52, -26, -54, -13, -8, -20, 37, -11, -2, 18, -3, 30, 7, 18, -4, -19, -40, -39, -50, -1, -13, -16, 31, -8, -36, 19, -3, 13, 5, -4, 17, -5, -46, -52, -43, 8, -27, -41, 47, 6, -13, 14, -25, 37, 5, 23, -3, -7, -78, -38, -49, -30, -8, -26, 17, 38, 0, 16, -29, 29, 20, -15, 3, 12, -63, -52, -44, -6, -9, 4, 50, 34, 4, 14, -4, 48, -6, 9, 12, 30, -41, -26, 
  17, -43, -13, -54, 26, -16, -5, 13, -55, -5, -61, -1, 2, 8, -8, -8, 20, -65, -27, -40, 14, 3, -19, 16, -56, 9, -36, 23, 12, 18, 14, -30, 4, -22, -43, -63, 20, 1, -18, 7, -40, -2, -33, 26, 30, 15, 7, -40, 6, -59, -24, -60, 15, 2, -29, 11, -43, -22, -65, 4, -18, 6, 14, -48, 35, -11, -9, -33, 21, -15, -20, 11, -25, 4, 8, -4, 16, 0, 17, -31, -18, 5, 9, 6, 3, 24, 30, -3, 8, -5, 8, 15, 12, 8, 29, 11, 16, -11, 3, 9, 22, 4, -11, 29, 21, 19, -9, 21, 9, 14, 18, -12, 6, -54, -19, -101, 2, -16, -27, -2, -49, -1, -77, -10, -18, -5, 15, -28, -3, -56, -10, -59, 9, -4, -45, 3, -42, 2, -20, -28, 3, -5, 26, -33, 15, -36, -11, -54, 18, -22, -24, 13, -43, 11, -54, 0, 27, -1, 21, -42, 3, -1, 4, -9, -6, -28, -15, 7, -21, -17, -66, -20, -17, 0, 13, -2, 23, -53, -20, -61, 7, 4, -2, 8, -46, -2, -60, -2, 25, -9, 12, -32, 0, -40, -33, -37, 6, 8, -15, -5, -36, 20, 5, -12, 25, 19, -1, -34, 20, -49, -26, -35, 9, -16, -23, 11, -46, 25, 20, -9, 32, 14, 8, -31, 26, -54, -12, -70, -2, -1, -24, 27, -21, 6, -45, 7, 1, 8, 10, -37, 23, -47, -6, -55, 9, 5, -26, -1, -32, -2, -36, 8, -6, 16, 19, -39, 4, -40, -17, -41, 23, -17, -44, -1, -32, 15, -64, -12, 8, 14, 24, -6, 14, -36, -21, -60, 0, 0, -26, 13, -67, 11, -35, 9, -2, 4, 2, -12, 15, -28, -22, -56, 12, -17, -23, 2, -41, -1, -59, -35, -11, -6, 32, -30, 7, -32, -44, -22, 0, -31, 5, 21, -32, 8, 5, 16, 25, 10, 27, -17, -7, -32, -30, -21, 10, -12, -19, 11, -31, 11, -63, 1, 13, 11, 3, -27, 9, -30, -27, -28, 12, -12, -33, 18, -48, -1, -48, -6, 5, 18, 5, -43, 25, -56, -21, -7, 16, -4, -8, 18, -28, 4, -27, -6, 3, -4, 6, -46, 22, -68, -34, -71, 10, 24, -22, 21, -56, -8, -19, -12, -5, 3, 18, -62, 11, -49, -79, -55, 10, 12, -21, 29, -64, 15, -36, -20, 13, 22, 7, -16, 
  -10, -4, 7, 18, -52, 10, 13, -11, 23, 1, -21, 52, 6, -25, 2, 5, 16, 20, 30, 19, -47, -17, 4, -14, 34, 9, 13, 30, 23, -48, 19, -10, 17, 9, -2, -5, -60, -48, 2, -19, 26, -10, 10, 28, 13, -87, 29, 7, -9, 13, 22, 11, -73, -24, -1, -31, 24, -3, -20, 31, 1, -33, 42, 7, -14, -5, 11, 8, -6, 33, 26, -15, 6, 28, 35, 30, 12, -19, -3, -25, -3, 3, 10, -30, -8, -10, 3, -17, -11, -23, -37, -24, 0, -23, -13, -2, -13, 16, -2, 5, -34, -26, 10, -26, -5, -7, 13, 29, -9, -13, -9, 12, -1, 21, 25, 3, -45, -3, 2, -28, 26, 3, 18, 26, -11, -30, 30, -5, 1, 4, 22, -11, -47, -21, 23, -40, 19, 9, 8, 31, 14, -48, 6, 16, -22, 5, 35, 10, -34, -16, 20, -26, 37, 6, -5, 16, 18, -26, 18, 18, -3, 11, -5, 4, -32, -2, 16, -27, 13, -4, 50, -1, -11, -25, 12, -5, 6, 28, 13, 9, -44, -37, 23, -31, 31, -4, -3, 14, -10, -42, 22, -10, 0, 12, 8, 14, -18, 18, 43, -17, 28, 13, 31, 12, 8, -20, 19, -8, -5, 22, 18, 6, -43, -1, 13, -14, 29, 14, 22, 33, -4, -45, 0, -7, 31, 27, 38, 0, -51, -40, 5, -12, 30, -1, 17, 30, 11, -32, 17, 6, -1, 27, 29, 13, -30, 15, 30, -35, 15, 2, 14, 17, 41, -29, 13, -8, 15, 13, 2, 12, -20, 30, 34, -21, 21, 0, 1, 10, 14, -42, 10, -13, 13, 23, 32, -7, -42, -16, 6, -3, 20, -3, 5, 45, 24, -57, -2, -2, 5, 0, 15, -2, -58, -7, 29, -16, 13, -8, 17, 55, 23, -41, 8, 0, -1, 19, 17, 17, -31, 5, 31, 4, 14, 26, 45, 19, -19, -54, 7, -7, 2, 7, 22, 16, -74, -37, 23, -28, 19, 5, 3, 58, -2, -59, 14, -16, 14, 13, 24, 8, -67, -28, 24, -27, 8, -5, 17, 43, 23, -45, 11, -8, 2, 21, 16, 15, -18, 18, 24, -29, 19, 18, 46, 29, 4, -65, 23, -26, 21, 6, 20, 2, -49, -3, 22, -1, 19, 23, 18, 38, 28, -59, 24, 1, 16, 5, 33, 2, -76, -24, -1, -36, 38, -12, 10, 42, 23, -64, 13, 0, 
  -41, -18, -33, 33, 0, -10, 20, -44, 11, 36, 36, 38, 8, -24, -68, -5, -34, -29, -18, 16, -17, -28, 32, -45, 26, 9, 9, 26, -17, -47, -94, 10, -53, 17, -20, -6, -25, -12, 2, -42, 4, -5, 14, -8, 2, -47, -62, 22, -45, 17, -14, 9, -55, -34, 30, -50, 9, 6, 6, 18, -26, -61, -56, 10, -21, 16, 25, 28, 0, -1, 11, -27, -4, 21, 10, -1, 3, -43, -46, 35, 1, -5, -3, -1, 20, -3, 0, -6, 2, -1, 31, 8, 2, 12, 1, 1, -3, 3, -7, 23, -30, -19, 12, 2, 8, 13, -1, 21, 2, 13, -7, -5, -31, 0, -13, 20, -21, -27, -3, -49, -22, 10, 3, 4, -16, -51, -54, 23, -45, -3, -18, 8, -23, -2, -2, -25, 0, 26, 20, 1, -9, -47, -102, 15, -53, -3, -23, 8, 3, -14, 6, -27, -3, 16, 23, -6, -23, -57, -44, 17, -26, -6, -6, 7, -33, -4, -2, -33, -6, 14, 5, 12, -11, -35, -64, -1, -23, 24, -25, 9, -3, -11, 8, -30, -20, 19, 25, 8, 19, -35, -52, 5, -39, -13, -37, 18, -13, -4, 26, -29, 7, 8, 23, -4, 10, -23, -20, 13, -35, -6, -20, 14, -10, -6, 9, -25, 15, 5, 22, -3, -20, -11, -54, 15, -37, -1, -27, 17, -7, -20, 5, -25, 4, -15, -6, -14, -4, -30, -36, 20, -55, -10, -30, 7, 6, -11, 6, -38, -7, 17, 7, -25, -24, -37, -39, 20, -72, 14, -35, 18, -18, 5, 2, -15, 12, -4, -5, -1, -43, -37, -53, 19, -54, 2, -36, 15, -26, 12, -1, -32, -17, -2, 10, -37, -12, -14, -40, 34, -45, 23, -6, -2, -27, -18, 2, -15, -9, -10, 0, -32, -26, -22, -21, 34, -69, -4, -27, 28, -6, 0, 17, -43, -3, 5, 12, -50, -43, -28, -22, 18, -52, -2, -10, 4, -3, 16, 29, -23, 13, 3, -5, -39, -11, -31, -38, 44, -30, 18, -18, 13, 17, -11, 16, -34, -6, -5, -2, -16, -44, 3, -46, 39, -54, -5, -17, 27, -2, 16, 7, -34, -6, 14, 37, -22, -35, -41, -46, 21, -24, -1, 6, 18, 7, 6, 15, -23, -24, 12, 15, -35, -52, -8, -51, 22, -29, 25, -2, 19, 6, -2, 3, -31, -10, -7, 4, -19, -37, -62, -50, 4, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 7,400 } };
const TfArray<1, float> quant7_scale = { 1, { 0.0059020412154495716, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[16] = { -1196, -4698, -4749, 505, 6001, -3178, -1166, -143, -4149, 3991, 202, -1691, -3819, 156, 1150, -395, };
const TfArray<1, int> tensor_dimension8 = { 1, { 16 } };
const TfArray<16, float> quant8_scale = { 16, { 5.7631354138720781e-05, 4.9643516831565648e-05, 4.7303958126576617e-05, 4.8535432142671198e-05, 5.244823478278704e-05, 9.2872971436008811e-05, 8.5747400589752942e-05, 5.7516223023412749e-05, 6.1228151025716215e-05, 6.258462235564366e-05, 8.4699953731615096e-05, 5.8249515859642997e-05, 5.2049916121177375e-05, 4.8669746320229024e-05, 6.5996660850942135e-05, 6.6220993176102638e-05, } };
const TfArray<16, int> quant8_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[16*1*3*8] = { 
  /* [0][0][][] */ -5,43,48,127,-64,-7,1,-10, -30,30,0,56,-39,-4,64,-54, -17,51,40,90,-31,-21,62,-29, 
  /* [1][0][][] */ 24,7,12,-2,82,-65,62,20, 1,-44,-19,54,127,-18,69,48, 118,-46,-2,-45,62,-117,84,-32, 
  /* [2][0][][] */ 28,-38,-43,88,50,-56,47,12, 123,-35,41,77,127,-105,45,23, -2,-17,2,10,65,-56,110,-41, 
  /* [3][0][][] */ 25,-6,5,-125,53,-5,-95,127, 0,-80,-38,6,15,0,-101,95, -17,1,-51,-36,-16,-30,10,82, 
  /* [4][0][][] */ -45,18,-93,-51,-85,-9,-82,8, -64,-8,-101,-52,-119,124,-78,0, 5,41,10,12,-74,127,-88,11, 
  /* [5][0][][] */ -98,38,22,-29,-37,-5,-62,40, -127,30,-3,-49,-17,28,-113,-8, -103,36,23,5,-36,10,-82,26, 
  /* [6][0][][] */ -22,-40,-24,19,-65,-11,-21,22, -27,-67,-36,-15,-35,-5,-15,66, -69,-127,-99,51,-46,-20,-111,-6, 
  /* [7][0][][] */ -60,53,-5,-28,-127,96,5,-3, 21,33,37,82,-43,56,-45,-16, -14,-11,-63,-2,-4,43,2,-36, 
  /* [8][0][][] */ 47,-91,26,64,52,-63,93,42, 25,-71,-55,56,127,-82,31,28, 38,-78,15,31,71,-47,46,-19, 
  /* [9][0][][] */ -55,-29,-36,45,-103,78,-45,32, -119,-40,-115,38,-78,42,-81,39, -37,-50,-101,127,-113,47,-57,51, 
  /* [10][0][][] */ -119,-75,-109,48,-66,-3,-41,4, -127,-108,-107,1,-72,-21,-123,35, -102,-78,-80,62,-95,15,-67,74, 
  /* [11][0][][] */ -107,-57,-77,87,36,-45,-45,-19, -65,-86,-17,39,56,-127,-15,34, -56,-99,-110,84,-79,-90,-86,-14, 
  /* [12][0][][] */ -53,15,-59,127,8,-25,97,-40, -23,-30,-104,1,-68,-19,-27,-29, 2,17,14,53,9,-91,-48,24, 
  /* [13][0][][] */ 50,46,48,-121,-82,73,-77,-20, 88,60,-2,-87,-127,-22,-108,-17, -12,30,108,-101,-23,4,-123,-3, 
  /* [14][0][][] */ 29,35,64,7,1,15,56,-127, 7,82,57,-23,9,3,59,-125, 40,-27,19,61,45,-12,19,-122, 
  /* [15][0][][] */ 93,5,16,-127,-13,-30,-68,77, 84,-25,27,-96,12,-34,-8,38, 65,-50,58,-115,-28,-31,14,57, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 16,1,3,8 } };
const TfArray<16, float> quant9_scale = { 16, { 0.0037095018196851015, 0.0031953565776348114, 0.0030447684694081545, 0.0031240335665643215, 0.0033758850768208504, 0.0059778653085231781, 0.0055192206054925919, 0.0037020912859588861, 0.003941013477742672, 0.0040283240377902985, 0.0054518003016710281, 0.0037492904812097549, 0.0033502469304949045, 0.0031326788011938334, 0.0042479434050619602, 0.0042623830959200859, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[8] = { 29728, -6646, 5591, -153, 18441, 4821, 21946, -11685, };
const TfArray<1, int> tensor_dimension10 = { 1, { 8 } };
const TfArray<8, float> quant10_scale = { 8, { 1.60026247613132e-05, 1.1925609214813448e-05, 1.1327722859277856e-05, 2.9540355171775445e-05, 1.9193816115148365e-05, 1.5411305867019109e-05, 1.8702701709116809e-05, 1.4294177162810229e-05, } };
const TfArray<8, int> quant10_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[8*1*3*40] = { 
  /* [0][0][][] */ 127,61,53,78,25,19,27,-35,-10,-47,-2,-67,-3,-82,-73,-64,-58,-72,-41,-62,16,-12,-13,-27,-32,-6,-36,-24,-24,-25,-25,10,23,-67,-10,1,-56,-29,-7,-28, 72,66,3,62,32,-5,44,29,16,-13,-1,-2,-84,15,0,-27,24,-28,-62,5,-89,44,-20,-11,-16,-43,49,32,19,-21,6,44,-54,-15,-44,-26,-13,-89,-50,-41, 118,75,120,-36,47,-10,-35,-12,-59,25,-47,-60,-38,-96,-64,-41,-93,-61,-22,-79,-26,-20,-39,-16,-65,-47,-47,2,7,20,-21,-51,5,-71,-46,-14,-30,7,-9,-10, 
  /* [1][0][][] */ -90,-48,-31,86,-4,89,30,78,15,19,-11,-75,-40,-2,94,29,-17,16,61,88,46,50,112,46,13,-18,-32,-14,-12,-14,11,-30,-32,-32,-49,-43,-70,-122,-57,-66, 2,-3,-31,57,50,69,89,79,59,-4,23,-57,-27,-5,11,82,55,6,-7,-2,97,100,79,52,-15,30,-18,-33,-50,22,-4,15,-38,-7,-87,-87,-97,-53,-127,-97, 20,-24,-13,-1,40,97,87,76,-6,37,-9,-26,10,3,38,77,33,65,50,46,25,104,82,108,26,71,-16,13,-16,-50,48,-23,-8,-51,-64,-3,-30,-71,-81,-6, 
  /* [2][0][][] */ 54,59,25,63,27,83,64,63,25,21,9,-107,-47,-47,-3,57,50,-13,27,58,47,96,65,72,28,-25,-46,-15,-19,-42,-53,-16,-63,-25,-10,-76,-4,-55,-61,-104, 46,14,56,9,68,114,84,8,103,-5,77,-94,-122,33,85,23,-52,-24,15,60,27,70,53,51,-14,24,-45,-6,-40,-79,-88,-10,-65,-38,-115,-64,-30,-28,-100,-63, 67,-55,15,16,119,78,99,121,93,-25,-35,-78,-96,1,43,3,-64,-34,30,-78,-6,41,-10,61,31,-88,-48,-76,-38,-58,-2,-88,-81,-127,1,-101,-10,-22,-81,-106, 
  /* [3][0][][] */ -127,-60,-48,-39,-10,-23,-21,3,-19,-35,-21,-3,18,3,-7,0,31,6,10,9,15,41,45,29,17,20,21,15,32,32,23,28,38,18,26,12,-2,5,-9,19, -98,-67,-63,-22,-30,-27,-10,-35,-9,1,-39,4,-9,0,-1,5,12,18,8,8,24,8,16,21,1,5,8,-1,29,18,21,32,20,8,-11,-15,8,-5,24,-9, -78,-58,-26,-59,-33,-37,-38,-28,-37,-32,-8,-16,-11,-19,-40,-11,-10,-17,-25,-4,-9,15,-8,-2,-1,-1,6,7,12,-5,5,-7,8,-10,-18,-3,-3,-21,-21,-7, 
  /* [4][0][][] */ -9,-48,-11,15,-16,-9,-25,-2,-5,-13,-56,1,-27,-38,-36,-39,-60,-88,-79,-48,-29,-26,-45,-50,-80,-32,-35,-8,-5,-26,0,-27,-30,9,32,-51,-21,-6,-3,-14, -45,13,-17,-25,-9,-13,-3,-25,-39,6,-41,-87,-55,-2,-87,-41,-55,-25,-40,-49,-28,40,5,-3,-39,-30,9,-33,10,16,-28,16,-7,-32,18,-1,-45,-27,-55,-4, 36,-32,-47,5,-48,-35,-15,9,-30,-60,9,-8,-6,-56,-64,-61,-127,-74,-34,-5,11,-38,-19,-44,-62,-68,-50,-6,-35,17,28,-4,12,-13,-28,-19,25,35,9,-39, 
  /* [5][0][][] */ 55,68,44,7,-9,2,-23,17,18,59,52,127,100,50,30,49,-1,30,-16,29,-35,15,42,-89,-25,-82,-3,15,-28,48,16,86,20,-7,13,-19,-24,-25,7,-25, 32,19,11,34,-28,-39,-38,-2,-9,20,55,62,57,46,21,43,29,-12,12,47,30,-8,-7,-17,-68,10,-41,-13,-1,17,37,39,-20,19,-25,-28,-26,10,-48,-46, 48,42,40,-30,-9,-29,-17,-12,34,69,67,93,79,49,-9,45,43,2,2,-72,-14,25,-37,-33,-56,-45,14,-6,-12,-31,85,57,-33,-44,-45,-48,-54,-37,4,15, 
  /* [6][0][][] */ -59,5,-27,18,0,-18,-61,-46,-61,-51,-22,-39,-33,-28,-29,-35,-56,10,-17,-47,-49,45,10,-50,-27,-31,25,-6,-33,5,33,6,30,-42,-14,4,-72,24,-27,-22, -93,-62,-6,-54,-57,42,-7,1,3,56,-35,-11,-38,-14,3,-64,-40,-51,-11,-27,-29,-21,-3,-65,-64,-24,-17,-8,-27,22,46,62,-47,-1,-78,0,22,16,-19,-45, -60,-39,-30,-24,-56,-37,-39,-24,-1,-2,-53,-52,-14,-127,-10,-60,-30,-66,-10,-32,-22,-42,18,0,-51,-16,-45,-43,-40,-3,26,23,-14,15,6,6,-47,-85,-28,-38, 
  /* [7][0][][] */ 122,35,57,45,39,49,17,23,-15,-25,-25,-75,-22,-76,-39,-31,-48,-13,-27,-23,-12,12,-3,5,8,6,40,49,52,53,18,6,34,69,34,39,71,45,68,40, 127,66,55,23,2,8,50,25,16,-4,-10,-62,-61,-44,-64,-53,-49,-68,-3,-20,-2,-5,24,32,10,-4,29,43,38,11,-28,30,57,50,77,60,49,61,31,59, 108,19,41,15,-2,30,7,-8,1,18,-80,-58,-106,-30,-24,-36,-21,-30,-2,-8,12,-10,3,31,-26,46,18,13,8,27,29,30,7,32,8,54,15,27,39,41, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 8,1,3,40 } };
const TfArray<8, float> quant11_scale = { 8, { 0.0040966719388961792, 0.0030529559589922428, 0.002899897051975131, 0.007562330923974514, 0.0049136169254779816, 0.003945294301956892, 0.0047878916375339031, 0.0036593093536794186, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,99,40 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,1,99,8 } };
const TfArray<1, float> quant13_scale = { 1, { 0.015536143444478512, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,99,1,8 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,50,1,8 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,50,8 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,50,16 } };
const TfArray<1, float> quant17_scale = { 1, { 0.014330849051475525, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,50,1,16 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,25,1,16 } };
const TfArray<2, int> tensor_dimension20 = { 2, { 1,400 } };
const TfArray<2, int> tensor_dimension21 = { 2, { 1,7 } };
const TfArray<1, float> quant21_scale = { 1, { 0.26894944906234741, } };
const TfArray<1, int> quant21_zero = { 1, { 55 } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&quant21_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 12 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 12,11,10 } };
const TfArray<1, int> outputs1 = { 1, { 13 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 13,2 } };
const TfArray<1, int> outputs2 = { 1, { 14 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 14 } };
const TfArray<1, int> outputs3 = { 1, { 15 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 15,3 } };
const TfArray<1, int> outputs4 = { 1, { 16 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 16,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 17 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 17,4 } };
const TfArray<1, int> outputs6 = { 1, { 18 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 18 } };
const TfArray<1, int> outputs7 = { 1, { 19 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 19,5 } };
const TfArray<1, int> outputs8 = { 1, { 20 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 20,7,6 } };
const TfArray<1, int> outputs9 = { 1, { 21 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 21 } };
const TfArray<1, int> outputs10 = { 1, { 22 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3968), (TfLiteIntArray*)&g0::tensor_dimension0, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 28, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 2800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3968), (TfLiteIntArray*)&g0::tensor_dimension13, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension15, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension17, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension19, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension21, 7, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 7, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 23, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  22, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1019536_9_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 23;
  for (size_t i = 0; i < 23; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1019536_9_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1019536_9_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1019536_9_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1019536_9_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
